import argparse

parser = argparse.ArgumentParser(description='Description of your script')
parser.add_argument('-d', '--deadline', help='deadline of the problem', nargs='?', default=None, type=int)
parser.add_argument('-st', '--search_time', help='amount of time in each step', nargs='?', default=1, type=int)
parser.add_argument('-sd', '--search_depth', help='search depth of ', nargs='?', default=40, type=int)
parser.add_argument('-se', '--selection_type', help='selection type in MCTS algorithm', nargs='?', default='avg')
parser.add_argument('-r', '--runs', help='how many runs to run the script', nargs='?', default=1, type=int)
parser.add_argument('-dt', '--domain_type', help='combination, new approach or new approach same as the baseline', nargs='?', default='regular')
parser.add_argument('-s', '--solver', help='solver', nargs='?', default='mcts')
parser.add_argument('-do', '--domain', help='domain')
parser.add_argument('-e', '--exploration_constant', help='the exploration constant for mcts solver', nargs='?', default=10, type=int)
parser.add_argument('-ge', '--garbage_amount', help='how many garbage actions to add to the domain', nargs='?', default=0, type=int)
parser.add_argument('-oe', '--object_amount', help='how many different objects in the domain', nargs='?', default=1, type=int)
parser.add_argument('-k', '--k', help='K random actions in the max planner', nargs='?', default=10, type=int)
parser.add_argument('-rm', '--reward_mode', help='reward mode: deadline or terminal', nargs='?', default='deadline')
parser.add_argument('--goal_reward_enabled', help='enable terminal/goal reward: 1 (on) or 0 (off)', nargs='?', default=1, type=int, choices=[0, 1])
parser.add_argument('--seed', help='random seed for reproducibility', nargs='?', default=None, type=int)
parser.add_argument('-hn', '--heuristic_samples', help='number of CRN heuristic scenarios to average', nargs='?', default=50, type=int)
parser.add_argument('-hm', '--heuristic_mode', help='heuristic mode: legacy | crn_fixed | crn_per_tree', nargs='?', default='crn_per_tree')

args = parser.parse_args()